### ISSUE TITLE
Bot timeout

### ISSUE THREAD

**Issue by SoniEx2** [notifico/notifico#127]
Make it so bots timeout (disconnect) after an hour of inactivity. Keeps the connection count low and solves the issue of the bots getting disconnected and causing the service to become unavailable.

**Comment by Dav1dde** [comment]
#120 is supposed to fix this issue, it is not yet deployed.

The problem with this workaround is, one notifico connection handles up to the maximum allowed number of channels as allowed by the IRC server, which is 100 on freenode, so finding a window of 1 hours is relativly hard, then if a window is found you need to make sure no messages are dropped (which might actually not that hard to implement). 

I would rather go for actually fixing the bug instead of including workarounds which might or might not work. Let's see how #120 works out.

**Comment by SoniEx2** [comment]
Fine. Do it like github instead.

**Comment by sckasturi** [comment]
side note: it's 120 chans on freenode, not 100
