### ISSUE TITLE
Site certificate expired

### ISSUE THREAD

**Issue by pyhedgehog** [notifico/notifico#166]
```console
# openssl s_client -connect n.tkte.ch:443 </dev/null 2>&1|grep notAfter
notAfter=Oct 26 23:59:59 2016 GMT
notAfter=Oct 26 23:59:59 2016 GMT
```

**Comment by Croydon** [comment]
I might be completely wrong, but it looks to me that @TkTech doesn't really want to host it. If I remember correctly he said at some point something along the lines of "I don't know why people are still using it".

Because of that and because he never response when people are asking how they can help, I might looking into offering some public hosting.

However, @TkTech it would be really nice if you could comment on the status of your public hosting and if you want to continue maintain it and if/how we can help ect.

**Comment by TkTech** [comment]
You're more than welcome to host your own instance, that was the original idea behind it and why it makes an effort to require 0 configuration to get running.

I do not offer support for my personal instance which spread through word-of-mouth. Supporting 3000+ projects on hundreds of channels and dozens of networks is not my idea of a fun weekend project.

That said I do make an effort to ensure everything is running smoothly and resolve errors as they pop up.  There are a few PRs that have been merged and not deployed, and a pending switch to letsencrypt. I'll see about doing so this weekend.
