### ISSUE TITLE
install an SSL certificate

### ISSUE THREAD

**Issue by Nowaker** [notifico/notifico#88]
Please install an SSL certificate. [StartSSL](https://www.startssl.com) provide them free of charge. Thanks!

**Comment by TkTech** [comment]
The public instance of notifico (n.tkte.ch) has supported SSL for some time. It does not redirect automatically.

**Comment by Mikaela** [comment]
It looks like in addition of not directing automatically it's missing HSTS.

**Comment by TkTech** [comment]
This is intentional and will not change. The auth page will likely support redirection, but the rest of the site I prefer you to use with HTTP.

My personal instance of notifico does not need the additional overhead of answering everything with SSL.

Your personal instance can easily support HTTPs-only.

**Comment by Mikaela** [comment]
I think the session can be captured when activity happens over http even if the auth page was secured.

**Comment by TkTech** [comment]
Yes, an SSL MITM can hijack any site that doesn't use HSTS (which is almost worthless on its own) combined with browser cert pinning.

Notifico has no problem working with an SSL site, so this isn't an issue for Notifico.

My *personal instance of notifico*, which I allow others to use, will not force SSL. Should you wish to enforce strict policies on your own instance, notifico has no problem supporting it.
